name: trafficAccident-env
dependencies: 
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - seaborn
  - pip
  - pip:
    - SciencePlots
    - opendatasets
    - missingno
    - miceforest
    - dython
    - geopandas
    - folium